const data = [
  {
    "id": "2.1",
    "Functional Objectives Category": "2.1 Promotion of  equipment safety based on safety audit(observation) for activities related to serious accident risks (such as falling, caught by, heavy equipment, chemical burns, burns, and electric shock)",
    "Functional Objectives": "2.1 Promotion of  equipment safety based on safety audit(observation) for activities related to serious accident risks (such as falling, caught by, heavy equipment, chemical burns, burns, and electric shock)",
    "Program": "2.1a Conduct 5 Internal Safety Audit per year (THPAL/CTS)",
    "KPI": "No. of Internal Safety Audit/year",
    "Target": "5",
    "YTD": "1",
    "Actual": "0",
    "Jan": "1",
    "Feb": "0",
    "Mar": "0",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.1",
    "Functional Objectives Category": "2.1 Promotion of  equipment safety based on safety audit(observation) for activities related to serious accident risks (such as falling, caught by, heavy equipment, chemical burns, burns, and electric shock)",
    "Functional Objectives": "",
    "Program": "2.1b 0 unresolved/ Open status Safety Audit findings after target date of completion",
    "KPI": "No. of unresolved/Open status Safety Audit findings after target date of completion",
    "Target": "0",
    "YTD": "6",
    "Actual": "0",
    "Jan": "4/9",
    "Feb": "2/11",
    "Mar": "0",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.2",
    "Functional Objectives Category": "2.2 Promotion of equipment safety through mutual safety audit ((observation) of routine activities by each departments and contractors",
    "Functional Objectives": "2.2 Promotion of equipment safety through mutual safety audit ((observation) of routine activities by each departments and contractors",
    "Program": "2.2 Safety Cross Audit for THPAL/Contractors Activities per year",
    "KPI": "No. of Safety Cross Audit",
    "Target": "2",
    "YTD": "1",
    "Actual": "0",
    "Jan": "0",
    "Feb": "1",
    "Mar": "0",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.3",
    "Functional Objectives Category": "2.3 Preventing similar incidents by reorganizing the safety education system for supervisors to provide effective safety instruction",
    "Functional Objectives": "2.3 Preventing similar incidents by reorganizing the safety education system for supervisors to provide effective safety instruction",
    "Program": "2.3 a Past Incident Categorization and Improvement of education methods and content (past incidents, SDS, rules, SOPs, KY, etc.)",
    "KPI": "Percentage of attendance of re-education",
    "Target": ">90%",
    "YTD": "95%",
    "Actual": "95%",
    "Jan": "-",
    "Feb": "-",
    "Mar": "95%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.3",
    "Functional Objectives Category": "2.3 Preventing similar incidents by reorganizing the safety education system for supervisors to provide effective safety instruction",
    "Functional Objectives": "",
    "Program": "2.3b Re-evaluation and education of countermeasures for past major incidents and environmental troubles",
    "KPI": "No. of Completed Review of Past Incident countermeasures",
    "Target": "6",
    "YTD": "2",
    "Actual": "-",
    "Jan": "1",
    "Feb": "1",
    "Mar": "-",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.4",
    "Functional Objectives Category": "2.4  Improving risk management capabilities through effective KY education for each department member",
    "Functional Objectives": "2.4  Improving risk management capabilities through effective KY education for each department member",
    "Program": "2.4a  Daily KY Card preparation before start of shift activities with Performace ratings",
    "KPI": "Percentage of compliance monthly",
    "Target": ">97%",
    "YTD": "98.8%",
    "Actual": "98.5%",
    "Jan": "99.1%",
    "Feb": "98.7%",
    "Mar": "98.5%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.4",
    "Functional Objectives Category": "2.4  Improving risk management capabilities through effective KY education for each department member",
    "Functional Objectives": "",
    "Program": "2.4b Conduct four (4) 4RKY Presentation per year + Twice (2) 1st and 2nd round 4RKY presentation for Plant wide (For the month of Nov - Dec)",
    "KPI": "No of 4RKY Presentation/year",
    "Target": "12",
    "YTD": "2",
    "Actual": "1",
    "Jan": "0",
    "Feb": "1",
    "Mar": "1",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.4",
    "Functional Objectives Category": "2.4  Improving risk management capabilities through effective KY education for each department member",
    "Functional Objectives": "",
    "Program": "2.4c  Unusual KY Card preparation and discussion to members before performing any Unusual Activity",
    "KPI": "Percentage of compliance in any Unusual Activity",
    "Target": "100%",
    "YTD": "100%",
    "Actual": "100%",
    "Jan": "100%",
    "Feb": "100%",
    "Mar": "100%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.5",
    "Functional Objectives Category": "2.5 Improve employees' knowledge and awareness on safety through continuous education",
    "Functional Objectives": "2.5 Improve employees' knowledge and awareness on safety through continuous education",
    "Program": "2.5a Daily Safety Declaration incorporating Safety Handbook",
    "KPI": "Percentage of compliance",
    "Target": ">85%",
    "YTD": ">66%",
    "Actual": "67%",
    "Jan": "73%",
    "Feb": "59%",
    "Mar": "67%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.5",
    "Functional Objectives Category": "2.5 Improve employees' knowledge and awareness on safety through continuous education",
    "Functional Objectives": "",
    "Program": "2.5b > 90% attendance of MS Safety Examination (MS Safety Group will make a scenario examination based from the updated Safety Handbook)",
    "KPI": "Percentage of attendance and compliance based from the MS Safety Examination",
    "Target": ">90%",
    "YTD": ">93%",
    "Actual": "89%",
    "Jan": "-",
    "Feb": "96%",
    "Mar": "89%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.5",
    "Functional Objectives Category": "2.5 Improve employees' knowledge and awareness on safety through continuous education",
    "Functional Objectives": "",
    "Program": "2.5c > 70% passing rate of MS personnels in Internal MS Safety Examination",
    "KPI": "Percentage of Examination taken by MS personnels (Given every Saturday)",
    "Target": ">70%",
    "YTD": ">94%",
    "Actual": "96%",
    "Jan": "-",
    "Feb": "91%",
    "Mar": "96%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.6",
    "Functional Objectives Category": "2.6 Promotion of measures to make up for weaknesses in each department that were identified during Safety Discussion",
    "Functional Objectives": "2.6 Promotion of measures to make up for weaknesses in each department that were identified during Safety Discussion",
    "Program": "2.6a Monthly Group Meeting related to Safety concerns per Group with MOM",
    "KPI": "Percentage of attendance",
    "Target": "100%",
    "YTD": "100%",
    "Actual": "100%",
    "Jan": "-",
    "Feb": "100%",
    "Mar": "100%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.6",
    "Functional Objectives Category": "2.6 Promotion of measures to make up for weaknesses in each department that were identified during Safety Discussion",
    "Functional Objectives": "",
    "Program": "2.6b Daily Toolbox Meeting compliance with Senior Foreman weekly observation",
    "KPI": "Percentage of compliance in any Unusual Activity",
    "Target": "100%",
    "YTD": "100%",
    "Actual": "100%",
    "Jan": "100%",
    "Feb": "100%",
    "Mar": "100%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.7",
    "Functional Objectives Category": "2.7 Reduce risk and maintain safe working conditions by conducting scheduled safety activities",
    "Functional Objectives": "2.7 Reduce risk and maintain safe working conditions by conducting scheduled safety activities",
    "Program": "2.7a Monthly PPE Inspection",
    "KPI": "Percentage of attendance and compliance monthly",
    "Target": "100%",
    "YTD": "100%",
    "Actual": "100%",
    "Jan": "100%",
    "Feb": "100%",
    "Mar": "100%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.7",
    "Functional Objectives Category": "2.7 Reduce risk and maintain safe working conditions by conducting scheduled safety activities",
    "Functional Objectives": "",
    "Program": "2.7b Monthly Lifting Gears and Accessories Inspection by Safety and Maintenance Department",
    "KPI": "Percentage of compliance monthly",
    "Target": "100%",
    "YTD": "100%",
    "Actual": "100%",
    "Jan": "100%",
    "Feb": "100%",
    "Mar": "100%",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "2.7",
    "Functional Objectives Category": "2.7 Reduce risk and maintain safe working conditions by conducting scheduled safety activities",
    "Functional Objectives": "",
    "Program": "2.7c Monthly Sulfur Building Water Flushing and Heat Stress Data Gathering",
    "KPI": "No. of compliance monthly",
    "Target": "12",
    "YTD": "3",
    "Actual": "1",
    "Jan": "1",
    "Feb": "1",
    "Mar": "1",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "3.1",
    "Functional Objectives Category": "3.1 Promotion of priority SD intiatives",
    "Functional Objectives": "3.1 Promotion of priority SD intiatives",
    "Program": "For minor SD: Focus on strengthening barricade management. Measures for major SD to be determined after minor SD review. Barricading Theme Actions: Educate on barricading procedures based on the Safety Manual. Ensure supplies for proper barricading are available. Incorporate barricading into daily and SD activities. Conduct patrols to assess barricading effectiveness in the field. Re-educate and address gaps found during patrols. Document barricading practices and share with OSH-Safety.",
    "KPI": "times per year",
    "Target": "2",
    "YTD": "1",
    "Actual": "1",
    "Jan": "-",
    "Feb": "-",
    "Mar": "1",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },  {
    "id": "3.2",
    "Functional Objectives Category": "3.2 Holding regular safety meetings (Monthly meeting with OSH-Safety)",
    "Functional Objectives": "3.2 Holding regular safety meetings (Monthly meeting with OSH-Safety)",
    "Program": "Summarize and report departmental safety issues. Attend monthly safety meetings and discuss action points. Update management on safety issues and reinforce messages in TO meetings.",
    "KPI": "once per month",
    "Target": "12",
    "YTD": "2",
    "Actual": "1",
    "Jan": "-",
    "Feb": "1",
    "Mar": "1",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  }
];