// Auto-generated from Excel at 2025-02-20 02:35:37
const incidents = [
  {"no": "1", "date": "Jan/03/2025", "record": "THPAL", "area": "LS", "type": "Operation", "level": "N/A", "classification": "Information Report", "osh_record": "N", "title": "111ML01 Running for 2 Hours No Load", "status": "IN-REVIEW", "under": "APrM", "pic": "Lumapat/Gayapa", "date_submitted": "1/6/2025", "deadline": "Jan/10/2025", "days_lapsed": "-4", "human": "completed", "equipment": "in-progress", "management": "in-progress", "finalreport": ""},
  {"no": "2", "date": "Jan/16/2025", "record": "CTS", "area": "FNTRL", "type": "Safety", "level": "2", "classification": "Fall on the same Level", "osh_record": "Y", "title": "CTS personnel fell down on chair at outside of FNTRL Resting area", "status": "CLOSED", "under": "Completed", "pic": "Capina/Aquino", "date_submitted": "1/18/2025", "deadline": "Jan/23/2025", "days_lapsed": "-5", "human": "completed", "equipment": "completed", "management": "completed", "finalreport": "\\\\thsugvmfs1\\Department\\Prod\\300 Incidents-Accidents\\02 Incident Report Present Year\\20250116 CTS personnel fell down on chair at outside of FNTRL Resting area\\Final Approved Report.pdf"},
  {"no": "3", "date": "Jan/22/2025", "record": "THPAL", "area": "MS", "type": "Environment", "level": "1", "classification": "Emission to Air", "osh_record": "Y", "title": "H2S Alarm at 106AI903 during NaSH totebin draining due to un-submerged Hose", "status": "CLOSED", "under": "Completed", "pic": "Capina/Aquino", "date_submitted": "1/24/2025", "deadline": "Jan/29/2025", "days_lapsed": "-5", "human": "completed", "equipment": "completed", "management": "completed", "finalreport": "\\G:\\Prod\\300 Incidents-Accidents\\02 Incident Report Present Year\\20250122 H2S Alarm at 106AI903 during NaSH totebin draining due to un-submerged Hose\\Final Approved Report.pdf"},
  {"no": "4", "date": "Jan/25/2025", "record": "THPAL", "area": "LS", "type": "Safety", "level": "1", "classification": "Fall from height", "osh_record": "Y", "title": "Stop-Go Frame fallen from 111HP01 during Maintenance activity", "status": "CLOSED", "under": "Completed", "pic": "Capina/Geraldino", "date_submitted": "2/2/2025", "deadline": "Feb/01/2025", "days_lapsed": "1", "human": "completed", "equipment": "in-progress", "management": "completed", "finalreport": "\\G:\\Prod\\300 Incidents-Accidents\\02 Incident Report Present Year\\20250125 Stop-Go Frame fallen from 111HP01 during Maintenance activity\\FINAL Approved Report.pdf"},
  {"no": "5", "date": "Jan/29/2025", "record": "THPAL", "area": "MS", "type": "Safety", "level": "1", "classification": "Fall from height", "osh_record": "Y", "title": "106CN01 Detached Pulley Cover Nearmiss", "status": "CLOSED", "under": "Completed", "pic": "Capina/Aquino", "date_submitted": "2/5/2025", "deadline": "Feb/05/2025", "days_lapsed": "0", "human": "completed", "equipment": "n/a", "management": "completed", "finalreport": "\\G:\\Prod\\300 Incidents-Accidents\\02 Incident Report Present Year\\20250129 106CN01 Detached Pulley Cover Nearmiss\\FINAL Approved Report.pdf"},
  {"no": "6", "date": "Jan/30/2025", "record": "THPAL", "area": "H2S", "type": "Operation", "level": "N/A", "classification": "Information Report", "osh_record": "N", "title": "109SR03 UNAVAIL due to LALL triggered", "status": "OPEN", "under": "E-file", "pic": "Capina/Aquino", "date_submitted": "2/13/2025", "deadline": "Feb/06/2025", "days_lapsed": "7", "human": "n/a", "equipment": "completed", "management": "in-progress", "finalreport": ""},
  {"no": "7", "date": "Feb/04/2025", "record": "THPAL", "area": "MS", "type": "Environment", "level": "1", "classification": "Emission to Air", "osh_record": "Y", "title": "H2S alarm at 106AI903 due to H2S leak from 106FN01", "status": "IN-REVIEW", "under": "SM", "pic": "Davis/Geraldino", "date_submitted": "2/9/2025", "deadline": "Feb/11/2025", "days_lapsed": "-2", "human": "n/a", "equipment": "in-progress", "management": "completed", "finalreport": ""},
  {"no": "8", "date": "Feb/04/2025", "record": "THPAL", "area": "MS", "type": "Environment", "level": "1", "classification": "Emission to Air", "osh_record": "Y", "title": "H2S Alarm at 106AI903 due to gap at liner at 105FN01A H2S Leak", "status": "IN-REVIEW", "under": "PrM", "pic": "Lauron/Villamor", "date_submitted": "2/5/2025", "deadline": "Feb/11/2025", "days_lapsed": "-6", "human": "n/a", "equipment": "in-progress", "management": "n/a", "finalreport": ""},
  {"no": "9", "date": "Feb/13/2025", "record": "THPAL", "area": "MS", "type": "Operation", "level": "N/A", "classification": "Information Report", "osh_record": "N", "title": "Community Paging Activation Incident", "status": "OPEN", "under": "Foreman", "pic": "Yamit/Baclayo", "date_submitted": "2/18/2025", "deadline": "Feb/20/2025", "days_lapsed": "-2", "human": "", "equipment": "", "management": "", "finalreport": ""}
];