const safetyData = [
  {
    "No.": "1",
    "Date": "7-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "1 General Rules",
    "SUBTOPIC": "1. 2 Behaviour",
    "Assigned": "MS",
    "2nd": "BOSQUE, Jonry",
    "3rd": "ROSILLO, King Mark",
    "1st": "URBIZTONDO, Grace",
    "Employee_Name": "AMALIAS, Carlo",
    "Area": "FNTRL",
    "Count": "0",
    "aaaa": "SL/MDCS"
  },  {
    "No.": "2",
    "Date": "8-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "1 General Rules",
    "SUBTOPIC": "1.3 Canteen",
    "Assigned": "FNTRL",
    "2nd": "GASAPO, Alladin",
    "3rd": "",
    "1st": "CERIO, Jenny Mae A.",
    "Employee_Name": "ANIB, Karl Patrick S.",
    "Area": "H2S",
    "Count": "2",
    "aaaa": "SDCS"
  },  {
    "No.": "3",
    "Date": "9-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "",
    "SUBTOPIC": "Safey Signage",
    "Assigned": "H2S",
    "2nd": "ARBIOL, Dann Jason A.",
    "3rd": "ANIB, Karl Patrick S.",
    "1st": "",
    "Employee_Name": "ARBIOL, Dann Jason A.",
    "Area": "SL/MDCS",
    "Count": "3",
    "aaaa": "MS"
  },  {
    "No.": "4",
    "Date": "10-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "1 General Rules",
    "SUBTOPIC": "1.7 Information Control",
    "Assigned": "LS",
    "2nd": "",
    "3rd": "",
    "1st": "BALACUIT,  Prince Joewen",
    "Employee_Name": "BADIANG, Luciano Jr.",
    "Area": "MS",
    "Count": "0",
    "aaaa": "H2S"
  },  {
    "No.": "5",
    "Date": "11-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "1 General Rules",
    "SUBTOPIC": "1.7 Information Control",
    "Assigned": "H2S",
    "2nd": "NUÑEZ, Reus",
    "3rd": "ANIB, Karl Patrick S.",
    "1st": "GIDA, Lenie Mae R.",
    "Employee_Name": "BALACUIT,  Prince Joewen",
    "Area": "LS",
    "Count": "2",
    "aaaa": "FNTRL"
  },  {
    "No.": "6",
    "Date": "12-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "4 Housekeeping",
    "SUBTOPIC": "All",
    "Assigned": "SDCS",
    "2nd": "ESTOLANO, Ronnie",
    "3rd": "ELLO, Janine",
    "1st": "NECESARIO, Christie P.",
    "Employee_Name": "BALACUIT, Jonesa Queen",
    "Area": "H2S",
    "Count": "2",
    "aaaa": "LS"
  },  {
    "No.": "7",
    "Date": "13-Jan-25",
    "CHAPTER": "1 General Plant Rules",
    "SECTION": "1 General Rules",
    "SUBTOPIC": "1. 4 General Safety Management",
    "Assigned": "SL/MDCS",
    "2nd": "MALONG, Brenda Glez",
    "3rd": "CIMAFRANCA, Emmanuel C.",
    "1st": "",
    "Employee_Name": "BANZON Jr., Nicanor R.",
    "Area": "LS",
    "Count": "3",
    "aaaa": ""
  },  {
    "No.": "8",
    "Date": "14-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "2 PPE Rules",
    "SUBTOPIC": "2.1 Special PPE (Inspection and Mangement)",
    "Assigned": "MS",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "BAYANG, Algemero",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "9",
    "Date": "15-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "2 PPE Rules",
    "SUBTOPIC": "All",
    "Assigned": "FNTRL",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "BAYETA, Louie",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "10",
    "Date": "16-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "3 Work Permit",
    "SUBTOPIC": "All",
    "Assigned": "H2S",
    "2nd": "",
    "3rd": "",
    "1st": "JABINAL, Jewel Mae",
    "Employee_Name": "BEROY, Jansenne Nicole",
    "Area": "H2S",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "11",
    "Date": "17-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "4 Isolation Policy",
    "SUBTOPIC": "All",
    "Assigned": "LS",
    "2nd": "JORTA, Jowei C.",
    "3rd": "BUYO, Rico Jay",
    "1st": "BANZON Jr., Nicanor R.",
    "Employee_Name": "BILAD, Marvin A.",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "12",
    "Date": "18-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "5 Lock Out/Tag Out Program",
    "SUBTOPIC": "All",
    "Assigned": "H2S",
    "2nd": "CAMINO, Jyzl E.",
    "3rd": "GIDA, Lenie Mae R.",
    "1st": "",
    "Employee_Name": "BOSQUE, Jonry",
    "Area": "SDCS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "13",
    "Date": "19-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "6 Hot work (Welding, oxy-acetylene cutting, chamfering, etc>)",
    "SUBTOPIC": "8.2 Coordination",
    "Assigned": "SDCS",
    "2nd": "",
    "3rd": "NECESARIO, Christie P.",
    "1st": "ESTOLANO, Ronnie",
    "Employee_Name": "BUYO, Rico Jay",
    "Area": "LS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "14",
    "Date": "20-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "7 Basic Rules for Tools",
    "SUBTOPIC": "All",
    "Assigned": "SL/MDCS",
    "2nd": "YAMIT, Junnil N.",
    "3rd": "PAGATPAT, Jeffrey C.",
    "1st": "DAPOSALA, Lenjo G.",
    "Employee_Name": "CAGAMPANG, Josan C.",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "15",
    "Date": "21-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "8 Basic Electical Rules",
    "SUBTOPIC": "All",
    "Assigned": "MS",
    "2nd": "MANILI, Jessie",
    "3rd": "GALVEZ, Jaypoy",
    "1st": "EUPEÑA. Joshua",
    "Employee_Name": "CAGATA, Renan A.",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "16",
    "Date": "22-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "9 Basic Mechanical Rule",
    "SUBTOPIC": "9.1 General Safety Pre",
    "Assigned": "FNTRL",
    "2nd": "LAPINING, Sanny Boy S.",
    "3rd": "PEROL, Remart",
    "1st": "YAMIT, John Paul P.",
    "Employee_Name": "CALIMBO, Romel",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "17",
    "Date": "23-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "10 SAFETY SIGNAGE AND BARRICADES",
    "SUBTOPIC": "All",
    "Assigned": "H2S",
    "2nd": "SANCHEZ, Pablo",
    "3rd": "ELCULLADA, Junmor S.",
    "1st": "MORILLA, Alora Kristy B.",
    "Employee_Name": "CAMINO, Jyzl E.",
    "Area": "H2S",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "18",
    "Date": "24-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "11 HIGH POWER TOOLS/RISK OF HIGH POWER",
    "SUBTOPIC": "All",
    "Assigned": "LS",
    "2nd": "",
    "3rd": "ESTILLORE, Marbert",
    "1st": "DOCOR, Romeo",
    "Employee_Name": "CAPIÑA, Jillian Marie B.",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "19",
    "Date": "25-Jan-25",
    "CHAPTER": "2 Basic Safety Rule",
    "SECTION": "12 MANAGEMENT AT CHANGING POINT",
    "SUBTOPIC": "All",
    "Assigned": "H2S",
    "2nd": "GIDA, Lenie Mae R.",
    "3rd": "",
    "1st": "TAYOR,  Rocar John Paul P.",
    "Employee_Name": "CARACOL, Marwin",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "20",
    "Date": "26-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "1 PALLET UTILITZATION AND MANAGEMEN",
    "SUBTOPIC": "All",
    "Assigned": "SDCS",
    "2nd": "NECESARIO, Christie P.",
    "3rd": "BOSQUE, Jonry",
    "1st": "",
    "Employee_Name": "CATONG, Abel",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "21",
    "Date": "27-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.1 On Falling Objects Protection",
    "Assigned": "SL/MDCS",
    "2nd": "PAGATPAT, Jeffrey C.",
    "3rd": "DAYOT, Ivy Mae",
    "1st": "YAMIT, Junnil N.",
    "Employee_Name": "CERIO, Jenny Mae A.",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "22",
    "Date": "28-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.2 On Power and Elevating Work Platforms",
    "Assigned": "MS",
    "2nd": "COMPASIVO, Jomar G.",
    "3rd": "LAUREJAS, Eduardo Jr. A",
    "1st": "DEGOLTO, Joel",
    "Employee_Name": "CIMAFRANCA, Emmanuel C.",
    "Area": "SL/MDCS",
    "Count": "4",
    "aaaa": ""
  },  {
    "No.": "23",
    "Date": "29-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.3 On Scaffolding",
    "Assigned": "FNTRL",
    "2nd": "KHO, Jansen D.",
    "3rd": "PATINO, Hernan L.",
    "1st": "RUDIS, June Mar",
    "Employee_Name": "CINCO, Richard",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "24",
    "Date": "30-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.4 On Stairs",
    "Assigned": "H2S",
    "2nd": "JABINAL, Jewel Mae",
    "3rd": "DELCORRO, Edgar S., Jr.",
    "1st": "",
    "Employee_Name": "COCAMAS, Louie R",
    "Area": "H2S",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "25",
    "Date": "31-Jan-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.5 On Ladders",
    "Assigned": "LS",
    "2nd": "BANZON Jr., Nicanor R.",
    "3rd": "ROZAL, DJ O.",
    "1st": "",
    "Employee_Name": "COLE, Kizza Yrl Wyeth",
    "Area": "SL/MDCS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "26",
    "Date": "1-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.6 On Personal Fall Arrest Systems",
    "Assigned": "H2S",
    "2nd": "JABINAL, Jewel Mae",
    "3rd": "",
    "1st": "BALACUIT, Jonesa Queen",
    "Employee_Name": "COMPASIVO, Jomar G.",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "27",
    "Date": "2-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.6 Requirements for working at heights with life line",
    "Assigned": "SDCS",
    "2nd": "ESTOLANO, Ronnie",
    "3rd": "",
    "1st": "NECESARIO, Christie P.",
    "Employee_Name": "CONSIGNA, Joel L.",
    "Area": "FNTRL",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "28",
    "Date": "3-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.7.B. Fall Restraint System",
    "Assigned": "SL/MDCS",
    "2nd": "ARBIOL, Dann Jason A.",
    "3rd": "CIMAFRANCA, Emmanuel C.",
    "1st": "LOZADA, Agafe Joy C.",
    "Employee_Name": "CORMINAL, Roland",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "29",
    "Date": "4-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.7.C. Pendulum Falls",
    "Assigned": "MS",
    "2nd": "ROSILLO, King Mark",
    "3rd": "",
    "1st": "",
    "Employee_Name": "DAGASDAS, Gregorio Jr.",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "30",
    "Date": "5-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.7.D. Safety Belt Falls",
    "Assigned": "FNTRL",
    "2nd": "GRAN, April Jane",
    "3rd": "",
    "1st": "",
    "Employee_Name": "DAPOSALA, Lenjo G.",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "31",
    "Date": "6-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "2 WORKING AT HEIGHTS",
    "SUBTOPIC": "2.7.E. Examples of Improper Connections",
    "Assigned": "H2S",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "DAYOT, Ivy Mae",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "32",
    "Date": "7-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "3 SCAFFOLDING ACTIVITY",
    "SUBTOPIC": "3.1 Erection- 3.2  Installation",
    "Assigned": "LS",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "DECAP, Anthony",
    "Area": "FNTRL",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "33",
    "Date": "8-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "3 SCAFFOLDING ACTIVITY",
    "SUBTOPIC": "3.3 Using of scaffolding ladder",
    "Assigned": "H2S",
    "2nd": "",
    "3rd": "",
    "1st": "JABINAL, Jewel Mae",
    "Employee_Name": "DEGOLTO, Joel",
    "Area": "MS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "34",
    "Date": "9-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "4.1 CONDUCT WORK AREA ASSESSMEN",
    "Assigned": "SDCS",
    "2nd": "",
    "3rd": "NECESARIO, Christie P.",
    "1st": "LAUREJAS, Eduardo Jr. A",
    "Employee_Name": "DELA PENA, Rapie S.",
    "Area": "LS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "35",
    "Date": "10-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "4.1 PREPARATION and GUIDELINES",
    "Assigned": "SL/MDCS",
    "2nd": "CAPIÑA, Jillian Marie B.",
    "3rd": "PAGATPAT, Jeffrey C.",
    "1st": "OCHAGAVIA, Johndel A.",
    "Employee_Name": "DELCORRO, Edgar S., Jr.",
    "Area": "H2S",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "36",
    "Date": "11-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "4.2 Working on Areas with Wheel Loader operation",
    "Assigned": "MS",
    "2nd": "",
    "3rd": "LUMAYNO, Junrey",
    "1st": "",
    "Employee_Name": "DOCOR, Romeo",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "37",
    "Date": "12-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "4.3 Working on Areas with Forklift Operation",
    "Assigned": "FNTRL",
    "2nd": "LAPINING, Sanny Boy S.",
    "3rd": "",
    "1st": "DECAP, Anthony",
    "Employee_Name": "ELCULLADA, Junmor S.",
    "Area": "H2S",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "38",
    "Date": "13-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "4.4 Working on Flat Truck",
    "Assigned": "H2S",
    "2nd": "WONG, Harold G.",
    "3rd": "NUÑEZ, Reus",
    "1st": "DELCORRO, Edgar S., Jr.",
    "Employee_Name": "ELLO, Janine",
    "Area": "SDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "39",
    "Date": "14-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "5.1 Hose Application",
    "Assigned": "LS",
    "2nd": "BUYO, Rico Jay",
    "3rd": "BANZON Jr., Nicanor R.",
    "1st": "GALENDEZ, Reyden",
    "Employee_Name": "ERCILLO, Marvin J.",
    "Area": "H2S",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "40",
    "Date": "15-Feb-25",
    "CHAPTER": "Exam",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "ESTILLORE, Marbert",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "41",
    "Date": "16-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "6.3.3 Lifting and lowering risk filter",
    "Assigned": "SDCS",
    "2nd": "URBIZTONDO, Grace",
    "3rd": "ESTOLANO, Ronnie",
    "1st": "SIMBAJON, Sherman Nove B.",
    "Employee_Name": "ESTOLANO, Ronnie",
    "Area": "SDCS",
    "Count": "6",
    "aaaa": ""
  },  {
    "No.": "42",
    "Date": "17-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "6.3.5 Carrying risk filter",
    "Assigned": "SL/MDCS",
    "2nd": "COLE, Kizza Yrl Wyeth",
    "3rd": "",
    "1st": "",
    "Employee_Name": "EUPEÑA. Joshua",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "43",
    "Date": "18-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "6.3.6 Pushing and pulling risk filter",
    "Assigned": "MS",
    "2nd": "BAYANG, Algemero",
    "3rd": "",
    "1st": "CATONG, Abel",
    "Employee_Name": "GALENDEZ, Reyden",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "44",
    "Date": "19-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "7: Lifting and Slinging",
    "Assigned": "FNTRL",
    "2nd": "DEGOLTO, Joel",
    "3rd": "YAMIT, John Paul P.",
    "1st": "DAGASDAS, Gregorio Jr.",
    "Employee_Name": "GALOS, Marlon",
    "Area": "FNTRL",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "45",
    "Date": "20-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "8.1 Chemical Safety Rules",
    "Assigned": "H2S",
    "2nd": "ELCULLADA, Junmor S.",
    "3rd": "SERAFIN, Fortunato L. Jr.",
    "1st": "",
    "Employee_Name": "GALVEZ, Jaypoy",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "46",
    "Date": "21-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "4 WORKING NEAR VEHICLE OR EQUIPMENT",
    "SUBTOPIC": "8.2 Compressed Gas Safety Rules",
    "Assigned": "LS",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "GASAPO, Alladin",
    "Area": "FNTRL",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "47",
    "Date": "22-Feb-25",
    "CHAPTER": "Exam",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "GIDA, Lenie Mae R.",
    "Area": "H2S",
    "Count": "3",
    "aaaa": ""
  },  {
    "No.": "48",
    "Date": "23-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "u",
    "SUBTOPIC": "3.1 Sulfuric Acid (H2SO4 98%)",
    "Assigned": "SDCS",
    "2nd": "ESTOLANO, Ronnie",
    "3rd": "MORDENO, Chelsea",
    "1st": "NECESARIO, Christie P.",
    "Employee_Name": "GRAN, April Jane",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "49",
    "Date": "24-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "8 HANDLING CHEMICALS AND COMPRESSED GAS",
    "SUBTOPIC": "3.4 Methanol",
    "Assigned": "H2S",
    "2nd": "ARBIOL, Dann Jason A.",
    "3rd": "TAYOR,  Rocar John Paul P.",
    "1st": "ERCILLO, Marvin J.",
    "Employee_Name": "HILVANO, Christian Joul P.",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "50",
    "Date": "25-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "8 HANDLING CHEMICALS AND COMPRESSED GAS",
    "SUBTOPIC": "3.3 Caustic Soda",
    "Assigned": "MS",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "JABINAL, Jewel Mae",
    "Area": "H2S",
    "Count": "4",
    "aaaa": ""
  },  {
    "No.": "51",
    "Date": "26-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "8 HANDLING CHEMICALS AND COMPRESSED GAS",
    "SUBTOPIC": "3.2 Slaked Lime",
    "Assigned": "",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "JAMERO, Donald",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "52",
    "Date": "27-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "8 HANDLING CHEMICALS AND COMPRESSED GAS",
    "SUBTOPIC": "3.5 Hydrogen Sulfide/H2S gas",
    "Assigned": "",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "JORTA, Jowei C.",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "53",
    "Date": "28-Feb-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "8 HANDLING CHEMICALS AND COMPRESSED GAS",
    "SUBTOPIC": "3.6 Carbon Monoxide (Co Gas)",
    "Assigned": "",
    "2nd": "",
    "3rd": "",
    "1st": "",
    "Employee_Name": "KHO, Jansen D.",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "54",
    "Date": "1-Mar-25",
    "CHAPTER": "Exam",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "LAPINING, Sanny Boy S.",
    "Area": "FNTRL",
    "Count": "3",
    "aaaa": ""
  },  {
    "No.": "55",
    "Date": "2-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "9 USING CUTTER AND SHARP TOOLS",
    "SUBTOPIC": "9.6 General Procedure to Follow Using Cutter",
    "Assigned": "SDCS",
    "2nd": "MORDENO, Chelsea",
    "3rd": "NECESARIO, Christie P.",
    "1st": "",
    "Employee_Name": "LAUREJAS, Eduardo Jr. A",
    "Area": "SDCS",
    "Count": "3",
    "aaaa": ""
  },  {
    "No.": "56",
    "Date": "3-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "10 RAM SOURCES",
    "SUBTOPIC": "12.1 Energization/De-Energization",
    "Assigned": "SL/MDCS",
    "2nd": "CIMAFRANCA, Emmanuel C.",
    "3rd": "LOZADA, Agafe Joy C.",
    "1st": "",
    "Employee_Name": "LAURON, Dini Daw M.",
    "Area": "H2S",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "57",
    "Date": "4-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "9 USING CUTTER AND SHARP TOOLS",
    "SUBTOPIC": "9.2 Scope and Definition of terms",
    "Assigned": "MS",
    "2nd": "CORMINAL, Roland",
    "3rd": "URBIZTONDO, Grace",
    "1st": "SOLAR, Ricardo Jr.",
    "Employee_Name": "LOZADA, Agafe Joy C.",
    "Area": "SL/MDCS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "58",
    "Date": "5-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "9 USING CUTTER AND SHARP TOOLS",
    "SUBTOPIC": "9.4 General Guidelines",
    "Assigned": "FNTRL",
    "2nd": "LAPINING, Sanny Boy S.",
    "3rd": "CARACOL, Marwin",
    "1st": "DECAP, Anthony",
    "Employee_Name": "LUMAYNO, Junrey",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "59",
    "Date": "6-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "9 USING CUTTER AND SHARP TOOLS",
    "SUBTOPIC": "9.3 Required PPE",
    "Assigned": "H2S",
    "2nd": "COCAMAS, Louie R",
    "3rd": "",
    "1st": "",
    "Employee_Name": "MAGLINTE, Jerryll A.",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "60",
    "Date": "7-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "9 USING CUTTER AND SHARP TOOLS",
    "SUBTOPIC": "9.1, 9.2. 9.7 Intro, Scope and Precautionary Measure",
    "Assigned": "LS",
    "2nd": "BALACUIT,  Prince Joewen",
    "3rd": "",
    "1st": "",
    "Employee_Name": "MALONG, Brenda Glez",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "61",
    "Date": "8-Mar-25",
    "CHAPTER": "Exam",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "MANILI, Jessie",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "62",
    "Date": "9-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "10 RAM SOURCES",
    "SUBTOPIC": "12.1 Energization/De-Energization",
    "Assigned": "H2S",
    "2nd": "BALACUIT, Jonesa Queen",
    "3rd": "LAURON, Dini Daw M.",
    "1st": "BEROY, Jansenne Nicole",
    "Employee_Name": "MARATAS, Ernie Mark",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "63",
    "Date": "10-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "10 RAM SOURCES",
    "SUBTOPIC": "4. ROLES AND RESPONSIBILITY",
    "Assigned": "SDCS",
    "2nd": "",
    "3rd": "ESTOLANO, Ronnie",
    "1st": "",
    "Employee_Name": "MORDENO, Chelsea",
    "Area": "SDCS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "64",
    "Date": "11-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "10 RAM SOURCES",
    "SUBTOPIC": "2.1 Definition",
    "Assigned": "SL/MDCS",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "MORILLA, Alora Kristy B.",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "65",
    "Date": "12-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NASAYAO, Dionesio",
    "Area": "LS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "66",
    "Date": "13-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NASAYAO, Flordecante",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "67",
    "Date": "14-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NASAYAO, Jesus",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "68",
    "Date": "15-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NECESARIO, Christie P.",
    "Area": "SDCS",
    "Count": "7",
    "aaaa": ""
  },  {
    "No.": "69",
    "Date": "16-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NECESARIO, Nhergil",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "70",
    "Date": "17-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "NUÑEZ, Reus",
    "Area": "H2S",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "71",
    "Date": "18-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "OCHAGAVIA, Johndel A.",
    "Area": "SL/MDCS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "72",
    "Date": "19-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "OCON, Jonathan P.",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "73",
    "Date": "20-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "ORCEJOLA, Karen Mae",
    "Area": "MS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "74",
    "Date": "21-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PADILLA, Chris Anthony",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "75",
    "Date": "22-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PAGATPAT, Jeffrey C.",
    "Area": "SL/MDCS",
    "Count": "3",
    "aaaa": ""
  },  {
    "No.": "76",
    "Date": "23-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PATINO, Hernan L.",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "77",
    "Date": "24-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PEROL, Remart",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "78",
    "Date": "25-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PLATERO, Paul Windell",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "79",
    "Date": "26-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "PRESILDA, Winston",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "80",
    "Date": "27-Mar-25",
    "CHAPTER": "SD period",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "ROBLES, Felmir",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "81",
    "Date": "28-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "11 CONFINE SPACE ENTRY CLEARANCE POLICY",
    "SUBTOPIC": "STANDARD AND MANAGEMENT",
    "Assigned": "LS",
    "2nd": "",
    "3rd": "",
    "1st": "JAMERO, Donald",
    "Employee_Name": "ROSILLO, King Mark",
    "Area": "MS",
    "Count": "2",
    "aaaa": ""
  },  {
    "No.": "82",
    "Date": "29-Mar-25",
    "CHAPTER": "Exam (cancelled)",
    "SECTION": "",
    "SUBTOPIC": "",
    "Assigned": "",
    "2nd": "n/a",
    "3rd": "n/a",
    "1st": "n/a",
    "Employee_Name": "ROZAL, DJ O.",
    "Area": "LS",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "83",
    "Date": "30-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "11 CONFINE SPACE ENTRY CLEARANCE POLICY",
    "SUBTOPIC": "STANDARD AND MANAGEMENT",
    "Assigned": "SDCS",
    "2nd": "LAUREJAS, Eduardo Jr. A",
    "3rd": "URBIZTONDO, Grace",
    "1st": "SIMBAJON, Sherman Nove B.",
    "Employee_Name": "RUDIS, June Mar",
    "Area": "FNTRL",
    "Count": "1",
    "aaaa": ""
  },  {
    "No.": "84",
    "Date": "31-Mar-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "11 CONFINE SPACE ENTRY CLEARANCE POLICY",
    "SUBTOPIC": "STANDARD AND MANAGEMENT",
    "Assigned": "SL/MDCS",
    "2nd": "CIMAFRANCA, Emmanuel C.",
    "3rd": "COLE, Kizza Yrl Wyeth",
    "1st": "",
    "Employee_Name": "SALABE, Mando C.",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "85",
    "Date": "1-Apr-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "13 PREVENTION OF HEAT ILLNESSS",
    "SUBTOPIC": "EDUCATION AND TRAINING",
    "Assigned": "MS",
    "2nd": "ORCEJOLA, Karen Mae",
    "3rd": "HILVANO, Christian Joul P.",
    "1st": "MARATAS, Ernie Mark",
    "Employee_Name": "SALON, Michael",
    "Area": "H2S",
    "Count": "0",
    "aaaa": ""
  },  {
    "No.": "86",
    "Date": "2-Apr-25",
    "CHAPTER": "3 RULES FOR SPECIAL WORK AND TOOLS/EQUIPMENT",
    "SECTION": "13 PREVENTION OF HEAT ILLNESSS",
    "SUBTOPIC": "COUNTERMEASURE AND TRAINING",
    "Assigned": "FNTRL",
    "2nd": "GASAPO, Alladin",
    "3rd": "",
    "1st": "",
    "Employee_Name": "SAMONTINA, Michael Jhun",
    "Area": "MS",
    "Count": "0",
    "aaaa": ""
  }
];