const data = [
  {
    "No.": "1",
    "Group": "1",
    "Year": "2024",
    "Month": "January",
    "Safety Program": "Internal Safety Audit",
    "Area": "H2S",
    "Topics": "209VE03 cold leg declogging",
    "Date Conducted": "1/30/2024",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "2",
    "Group": "4",
    "Year": "2024",
    "Month": "January",
    "Safety Program": "4RKY Presentation",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "3",
    "Group": "4",
    "Year": "2024",
    "Month": "February",
    "Safety Program": "Internal Safety Audit for Contractors",
    "Area": "LS",
    "Topics": "111BC02/04 Catcher clean-up",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "4",
    "Group": "1",
    "Year": "2024",
    "Month": "February",
    "Safety Program": "4RKY Presentation",
    "Area": "FNTRL",
    "Topics": "",
    "Date Conducted": "2/22/2024",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "5",
    "Group": "All",
    "Year": "2024",
    "Month": "February",
    "Safety Program": "Safety Cross Audit with VSLC",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "6",
    "Group": "2",
    "Year": "2024",
    "Month": "March",
    "Safety Program": "Internal Safety Audit",
    "Area": "MS",
    "Topics": "106ML02 operation",
    "Date Conducted": "3/21/2024",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "7",
    "Group": "3",
    "Year": "2024",
    "Month": "March",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "H2S",
    "Topics": "H2/Sulfur /H2S Area/MS/DeZn",
    "Date Conducted": "3/19/2024",
    "Status": "Completed",
    "Remarks": "HPAL Winner"
  },  {
    "No.": "8",
    "Group": "All",
    "Year": "2024",
    "Month": "April",
    "Safety Program": "SD Re-education",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "9",
    "Group": "2",
    "Year": "2024",
    "Month": "May",
    "Safety Program": "4RKY Presentation",
    "Area": "LS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "10",
    "Group": "3",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "Internal Safety Audit for Contractors",
    "Area": "FNTRL",
    "Topics": "Flocculant Charging",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "11",
    "Group": "4",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "Internal Safety Audit",
    "Area": "FNTRL",
    "Topics": "108 launder sampling",
    "Date Conducted": "6/29/2024",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "12",
    "Group": "All",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "Safety Cross Audit for Contractor Activities",
    "Area": "MS",
    "Topics": "106 Reactor sampling",
    "Date Conducted": "6/30/2024",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "13",
    "Group": "4",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "",
    "Topics": "HPAL Activity",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": "MS Winner"
  },  {
    "No.": "14",
    "Group": "All",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "Schedule for small group safety discussion",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "15",
    "Group": "All",
    "Year": "2024",
    "Month": "June",
    "Safety Program": "Elimination of traffic accidents",
    "Area": "All",
    "Topics": "RE-sducation sched",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "16",
    "Group": "All",
    "Year": "2024",
    "Month": "July",
    "Safety Program": "Schedule for small group safety discussion",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "17",
    "Group": "2",
    "Year": "2024",
    "Month": "July",
    "Safety Program": "Safety Cross Audit for THPAL Activities",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "18",
    "Group": "1",
    "Year": "2024",
    "Month": "July",
    "Safety Program": "4RKY Presentation",
    "Area": "FNTRL",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "19",
    "Group": "3",
    "Year": "2024",
    "Month": "August",
    "Safety Program": "Internal Safety Audit",
    "Area": "LS",
    "Topics": "111PU02 suction strainer clean-up",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "20",
    "Group": "2",
    "Year": "2024",
    "Month": "August",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "H2S",
    "Topics": "H2/Sulfur /H2S Area",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": "MS Winner"
  },  {
    "No.": "21",
    "Group": "All",
    "Year": "2024",
    "Month": "August",
    "Safety Program": "Safety Cross Audit with VSLC",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "22",
    "Group": "All",
    "Year": "2024",
    "Month": "September",
    "Safety Program": "SD Re-education",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "23",
    "Group": "2",
    "Year": "2024",
    "Month": "October",
    "Safety Program": "Internal Safety Audit for Contractors",
    "Area": "MS",
    "Topics": "Polishing filter Cloth washing",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "24",
    "Group": "3",
    "Year": "2024",
    "Month": "October",
    "Safety Program": "Safety Cross Audit for THPAL Activities",
    "Area": "Scandium",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "25",
    "Group": "3",
    "Year": "2024",
    "Month": "October",
    "Safety Program": "4RKY Presentation",
    "Area": "LS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "26",
    "Group": "1",
    "Year": "2024",
    "Month": "November",
    "Safety Program": "Internal Safety Audit",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "27",
    "Group": "4",
    "Year": "2024",
    "Month": "November",
    "Safety Program": "Safety Cross Audit for Contractor Activities",
    "Area": "Admin",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "28",
    "Group": "3",
    "Year": "2024",
    "Month": "November",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "29",
    "Group": "4",
    "Year": "2024",
    "Month": "December",
    "Safety Program": "4RKY Presentation",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "cancelled",
    "Remarks": ""
  },  {
    "No.": "30",
    "Group": "1",
    "Year": "2025",
    "Month": "January",
    "Safety Program": "Internal Safety Audit (THPAL/CTS)",
    "Area": "LS",
    "Topics": "111BC05 Flushing",
    "Date Conducted": "1/9/2025",
    "Status": "completed",
    "Remarks": ""
  },  {
    "No.": "31",
    "Group": "3",
    "Year": "2025",
    "Month": "January",
    "Safety Program": "Safety Cross Audit with VSLC",
    "Area": "THPAL",
    "Topics": "WWA Transfer and Management",
    "Date Conducted": "1/28/2025",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "32",
    "Group": "All",
    "Year": "2025",
    "Month": "April",
    "Safety Program": "Safety Cross Audit with VSLC",
    "Area": "VSLC",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Rescheduled by THPAL Safety",
    "Remarks": ""
  },  {
    "No.": "33",
    "Group": "4",
    "Year": "2025",
    "Month": "February",
    "Safety Program": "4RKY Presentation",
    "Area": "",
    "Topics": "",
    "Date Conducted": "2/20/2025",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "34",
    "Group": "2",
    "Year": "2025",
    "Month": "February",
    "Safety Program": "Safety Cross Audit for Contractor Activities",
    "Area": "LS",
    "Topics": "111ML01 steelballs charging",
    "Date Conducted": "2/13/2025",
    "Status": "Completed",
    "Remarks": "Auditor: E&I"
  },  {
    "No.": "35",
    "Group": "All",
    "Year": "2025",
    "Month": "March",
    "Safety Program": "SD Re-education",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "36",
    "Group": "3",
    "Year": "2025",
    "Month": "April",
    "Safety Program": "Internal Safety Audit",
    "Area": "H2S",
    "Topics": "109TK02 vent line declogging",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "37",
    "Group": "3",
    "Year": "2025",
    "Month": "April",
    "Safety Program": "4RKY Presentation",
    "Area": "H2S",
    "Topics": "109TK02 vent line declogging",
    "Date Conducted": "",
    "Status": "Completed",
    "Remarks": ""
  },  {
    "No.": "38",
    "Group": "1",
    "Year": "2025",
    "Month": "May",
    "Safety Program": "Internal Safety Audit",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "39",
    "Group": "4",
    "Year": "2025",
    "Month": "May",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "",
    "Topics": "HPAL Activity",
    "Date Conducted": "",
    "Status": "2-May",
    "Remarks": "Host: HPAL"
  },  {
    "No.": "40",
    "Group": "2",
    "Year": "2025",
    "Month": "June",
    "Safety Program": "Internal Safety Audit",
    "Area": "FNTRL",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "41",
    "Group": "1",
    "Year": "2025",
    "Month": "June",
    "Safety Program": "4RKY Presentation",
    "Area": "H2S",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "42",
    "Group": "1",
    "Year": "2025",
    "Month": "July",
    "Safety Program": "Safety Cross Audit for THPAL Activities",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "43",
    "Group": "2",
    "Year": "2025",
    "Month": "July",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "HPAL",
    "Topics": "HPAL Activity",
    "Date Conducted": "",
    "Status": "",
    "Remarks": "Host (MS)"
  },  {
    "No.": "44",
    "Group": "4",
    "Year": "2025",
    "Month": "August",
    "Safety Program": "Internal Safety Audit (THPAL/CTS)",
    "Area": "LS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "45",
    "Group": "All",
    "Year": "2025",
    "Month": "August",
    "Safety Program": "Safety Cross Audit with VSLC",
    "Area": "THPAL",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "46",
    "Group": "2",
    "Year": "2025",
    "Month": "August",
    "Safety Program": "4RKY Presentation",
    "Area": "LS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "47",
    "Group": "All",
    "Year": "2025",
    "Month": "September",
    "Safety Program": "SD Re-education",
    "Area": "All",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "48",
    "Group": "3",
    "Year": "2025",
    "Month": "October",
    "Safety Program": "Internal Safety Audit (THPAL/CTS)",
    "Area": "MS",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  },  {
    "No.": "49",
    "Group": "1",
    "Year": "2025",
    "Month": "October",
    "Safety Program": "4RKY Presentation (Competition)",
    "Area": "TBD",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": "Host (HPAL)"
  },  {
    "No.": "50",
    "Group": "4",
    "Year": "2025",
    "Month": "November",
    "Safety Program": "Safety Cross Audit for THPAL Activities",
    "Area": "Scandium",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": "Auditor: SC"
  },  {
    "No.": "51",
    "Group": "3",
    "Year": "2025",
    "Month": "December",
    "Safety Program": "Safety Cross Audit for Contractor Activities",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": "Auditee: Chromite"
  },  {
    "No.": "52",
    "Group": "All",
    "Year": "2025",
    "Month": "December",
    "Safety Program": "Plant wide 4RKY Presentation (Competition)",
    "Area": "",
    "Topics": "",
    "Date Conducted": "",
    "Status": "",
    "Remarks": ""
  }
];